version: 2
updates:
  # Keep Ruby dependencies up to date
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "whodunit-gem/maintainers"
    assignees:
      - "whodunit-gem/maintainers"
    labels:
      - "dependencies"
      - "ruby"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "whodunit-gem/maintainers"
    assignees:  
      - "whodunit-gem/maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"