module Whodunit
  module Chronicles
    class LedgerFactory
      def self.build: (Hash[untyped, untyped] config) -> Ledger
      def initialize: (Hash[untyped, untyped] config) -> void
      def build: () -> Ledger

      private

      def stringify_keys: (untyped value) -> untyped
      def required_value: (Hash[String, untyped] config, String key) -> untyped
    end
  end
end
